package rpc

const (
	Chain33_Lock                  = "Chain33.Lock"
	Chain33_UnLock                = "Chain33.UnLock"
	Chain33_SetPasswd             = "Chain33.SetPasswd"
	Chain33_SetLabel              = "Chain33.SetLabel"
	Chain33_NewAccount            = "Chain33.NewAccount"
	Chain33_GetAccounts           = "Chain33.GetAccounts"
	Chain33_MergeBalance          = "Chain33.MergeBalance"
	Chain33_SetTxFee              = "Chain33.SetTxFee"
	Chain33_SendToAddress         = "Chain33.SendToAddress"
	Chain33_ImportPrivKey         = "Chain33.ImportPrivKey"
	Chain33_WalletTransactionList = "Chain33.WalletTransactionList"
	Chain33_GetTicketCount        = "Chain33.GetTicketCount"
	Chain33_DumpPrivkey           = "Chain33.DumpPrivkey"
	Chain33_SignRawTx             = "Chain33.SignRawTx"
	Chain33_GetMempool            = "Chain33.GetMempool"
	Chain33_SendTransaction       = "Chain33.SendTransaction"
	Chain33_CreateRawTransaction  = "Chain33.CreateRawTransaction"
	Chain33_SendRawTransaction    = "Chain33.SendRawTransaction"
	Chain33_QueryTransaction      = "Chain33.QueryTransaction"
	Chain33_GetTxByAddr           = "Chain33.GetTxByAddr"
	Chain33_GetTxByHashes         = "Chain33.GetTxByHashes"
	Chain33_GetHexTxByHash        = "Chain33.GetHexTxByHash"
	Chain33_GetAddrOverview       = "Chain33.GetAddrOverview"
	Chain33_Version               = "Chain33.Version"
	Chain33_GetBlocks             = "Chain33.GetBlocks"
	Chain33_GetLastHeader         = "Chain33.GetLastHeader"
	Chain33_GetHeaders            = "Chain33.GetHeaders"
	Chain33_GetBlockHash          = "Chain33.GetBlockHash"
	Chain33_GetBlockOverview      = "Chain33.GetBlockOverview"
	Chain33_GetPeerInfo           = "Chain33.GetPeerInfo"
	Chain33_GetNetInfo            = "Chain33.GetNetInfo"
	Chain33_GenSeed               = "Chain33.GenSeed"
	Chain33_SaveSeed              = "Chain33.SaveSeed"
	Chain33_GetSeed               = "Chain33.GetSeed"
	Chain33_GetWalletStatus       = "Chain33.GetWalletStatus"
	Chain33_GetBalance            = "Chain33.GetBalance"
	Chain33_GetTokenBalance       = "Chain33.GetTokenBalance"
	Chain33_Query                 = "Chain33.Query"
	Para_IsSync                   = "paracross.IsSync"
	Chain33_IsSync                = "Chain33.IsSync"
)
